# Ex5A_NumPy_fundamentals

In [1]:
import numpy as np

## Array Basics 

In [2]:
# Fruit Variables
fruits = ["apple", "banana", "cherry", "date"]

In [3]:
# Create Numpy Array
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [4]:
# Checking Data Type 
print(arr_1.dtype)

<U6


In [5]:
# Creat 2-D Array 
arr_2 = np.array([[10, 11, 12], 
                  [13, 14, 15]])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
# Transpose 
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [7]:
# Checking to see if arr_2 changed 
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [8]:
#No, this does not change arr_2 permanently. Just the format temporarily
#(.T) only returns a transposed view, it doesn't modify the original array.

In [9]:
# Creating another 2-D Array 
arr_3 = np.array([[1, 3, 5],
                  [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [10]:
# Using Slicing with an Array 
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])

print(arr_4)

[5 4]


In [11]:
# Creating 3-D Array (creates array of all 1's)
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
