# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np 

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


### The first loop iterates through the rows (first dimension) of the array, so each iteration processes an entire row at once. When multiplied by 2, the whole row is doubled as a group.
### The second loop goes deeper into the array by iterating through each element (second dimension). Instead of working with rows, it prints each individual number multiplied by 2.

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [20]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

ValueError: all input arrays must have the same shape

In [11]:
# This raises a ValueError because np.stack requires all arrays to have the same shape.
# joined_array_1 has shape (4, 3) while joined_array_2 has shape (2, 6),
# so NumPy cannot stack them together.

In [12]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [13]:
# another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# print(another_2)

# Error explanation:
# This fails because the arrays do not have the same number of rows.
# For axis=1 concatenation, the number of rows (dimension 0) must match.
# joined_array_1 has more rows than arrA, so NumPy cannot align them.

In [33]:
hstack_result = np.hstack((arrA, arrA))
print(hstack_result)
print()
# hstack stacks arrays horizontally (side by side, like axis=1)

vstack_result = np.vstack((arrA, arrA))
print(vstack_result)
print()
# vstack stacks arrays vertically (on top of each other, like axis=0)

dstack_result = np.dstack((arrA, arrA))
print(dstack_result)
print()
# dstack stacks arrays along a new third dimension (depth), creating layers

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]



 ## Splitting Arrays

In [26]:
#Split into 2 Arrays
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [27]:
# Result description:
# This creates a list of 2 arrays.
# Each array is still 2-dimensional, and each contains half of the rows from joined_array_1.
# So if joined_array_1 has shape (4, 3), each split will have shape (2, 3).

In [28]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [29]:
# Result description:
# This creates a list of 3 arrays.
# Each array is still 2-dimensional, but they may not all have equal sizes.
# Since 4 rows cannot be divided evenly into 3 parts, NumPy distributes them as evenly as possible.
# For example, you may get arrays with shapes like (2, 3), (1, 3), and (1, 3).

## Searching and Replacing Array Values

In [30]:
#If the number is odd, it replaces it with the string 'odd'
## If the number is even (arrA % 2 == 0), it keeps the original value
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [31]:
#Create and Sort arrB
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [32]:
#Filter Values Less Than 7
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [25]:
#Filter Values Greater Than or Equal to 7
y = arrB >= 7
arrD = arrB[y]

print(arrD)

[ 7 13  7]
