# Exercise 1.B NumPy Random

In [1]:
import numpy as np 

## Generating Random Numbers

### r1

In [6]:
# Random ints between 1 and 20 (size = 2 int)
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[15 19]


### r2

In [9]:
# Random int between 1 and 20 (1 row, 2 columns)
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[ 1 10]]


### r3

In [10]:
# Random floats between 0 and 1 (2 rows, 1 column)
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.77425215]
 [0.83951037]]


### r4

In [11]:
# Random int between 20 and 100 (4 rows, 5 columns)
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[58 48 42 77 89]
 [44 55 68 40 37]
 [59 92 53 84 21]
 [81 60 40 93 33]]


### r5

In [12]:
# Random floats between 0 and 1 (4 rows, 5 columns)
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.91325443 0.34013055 0.87331061 0.44661953 0.87109014]
 [0.69563544 0.53088989 0.5791712  0.74227474 0.75777691]
 [0.33309121 0.03174069 0.32556301 0.80904569 0.11250036]
 [0.43036349 0.42107165 0.68592134 0.30820946 0.27368007]]


## Generating Random Choices from an Array

#### Creating Students: 1-D array of 12 classmates in YUU

In [13]:
students = np.array([
    "Lesley", "Corey", "Lorah", "Alondra",
    "Victoria", "Alexus", "Blake", "Tihitina",
    "Hana", "Charles", "Luis", "Smaya"
])

print(students)

['Lesley' 'Corey' 'Lorah' 'Alondra' 'Victoria' 'Alexus' 'Blake' 'Tihitina'
 'Hana' 'Charles' 'Luis' 'Smaya']


In [14]:
# Randomly select one student
call_on = np.random.choice(students)
print(call_on)

Alexus


### Creating Breakout groups 

In [24]:
# Random sampling into a 3x4 group (3, 4)
breakout_groups = np.random.choice(students, size=(3, 4))
print(f"Breakout Groups: \n" ,breakout_groups)

Breakout Groups: 
 [['Alexus' 'Alondra' 'Lesley' 'Alondra']
 ['Lesley' 'Blake' 'Hana' 'Alexus']
 ['Luis' 'Lorah' 'Blake' 'Luis']]


In [18]:
# Comment:
# This is NOT an effective way to assign breakout groups because
# students can be selected more than once (duplicates),
# and some students might not be selected at all.
# This makes the grouping unfair and uneven.

### Create statement for 5 random selections of students 

In [23]:
p_values = [0.0, 0.30, 0.10, 0.08,
            0.07, 0.07, 0.08, 0.08,
            0.07, 0.05, 0.05, 0.05]

call_on_weighted = np.random.choice(students, size=5, p=p_values)
print(f"Random Students: \n" ,call_on_weighted)

Random Students: 
 ['Alexus' 'Alondra' 'Victoria' 'Lorah' 'Alexus']


## Generating a Normal Distribution

#### Create a normal (bell curve) distribution

In [25]:
# mean = 10, standard deviation = 5, size = (4, 5)

bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(f"Bell Curve: \n", bell_curve)

Bell Curve: 
 [[10.23606089 11.79638582 13.53133089 12.63981955 10.93522116]
 [13.70224921  9.11065095 15.26901466 15.93505003 15.60110105]
 [11.82061724  9.33639936  8.45383061  7.72352003  4.48190472]
 [ 8.42398472 18.24468556  8.7700493   8.82991288 15.62273437]]
