# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np 

## Sample Arrays 

In [2]:
#Recreating arrays from Exercise 1.B

# r_1: 1D array of 2 random integers (1–20)
r_1 = np.random.randint(1, 21, size=2)

# r_2: 1 row, 2 columns (integers 1–20)
r_2 = np.random.randint(1, 21, size=(1, 2))

# r_3: 2 rows, 1 column (floats 0–1)
r_3 = np.random.rand(2, 1)

# r_4: 4 rows, 5 columns (integers 20–100)
r_4 = np.random.randint(20, 101, size=(4, 5))

# r_5: 4 rows, 5 columns (floats 0–1)
r_5 = np.random.rand(4, 5)

In [4]:
# Print all arrays from 1.B
print("r_1:\n", r_1)
print()
print("r_2:\n", r_2)
print()
print("r_3:\n", r_3)
print()
print("r_4:\n", r_4)
print()
print("r_5:\n", r_5)
print()

r_1:
 [7 1]

r_2:
 [[4 4]]

r_3:
 [[0.97151922]
 [0.22000754]]

r_4:
 [[ 78  27  53  34  63]
 [ 80  64  55  90  96]
 [ 84  30  94  45  80]
 [100  47  38  43  64]]

r_5:
 [[0.9497688  0.01780817 0.33242869 0.10375866 0.89392696]
 [0.0813127  0.50057308 0.44379102 0.41364834 0.0405875 ]
 [0.62222827 0.97680771 0.14367897 0.72005457 0.13435619]
 [0.95133862 0.41957458 0.15196848 0.96833663 0.13256665]]



## Permutations

### *refers to an arrangement of elements in a specific order, where the order matters*

In [5]:
# current output for r_4
print("Original r_4:\n", r_4)

Original r_4:
 [[ 78  27  53  34  63]
 [ 80  64  55  90  96]
 [ 84  30  94  45  80]
 [100  47  38  43  64]]


#### Shuffle r_4

In [6]:
np.random.shuffle(r_4)

# Print shuffled r_4
print("Shuffled r_4:\n", r_4)

Shuffled r_4:
 [[ 80  64  55  90  96]
 [100  47  38  43  64]
 [ 78  27  53  34  63]
 [ 84  30  94  45  80]]


In [7]:
# After using np.random.shuffle, the rows of r_4 were rearranged,
# but the values within each row stayed in the same order.
# This is because shuffle only rearranges elements along the first axis
# (rows for a 2D array), not the individual elements inside each row.

#### Create a new shuffled version without changing the original

In [8]:
new_shuffle = np.random.permutation(r_4)

print("New shuffled array:\n", new_shuffle)
print("\nCurrent r_4 (unchanged after permutation):\n", r_4)

New shuffled array:
 [[ 80  64  55  90  96]
 [100  47  38  43  64]
 [ 78  27  53  34  63]
 [ 84  30  94  45  80]]

Current r_4 (unchanged after permutation):
 [[ 80  64  55  90  96]
 [100  47  38  43  64]
 [ 78  27  53  34  63]
 [ 84  30  94  45  80]]


In [ ]:
# np.random.shuffle changes the original array by rearranging its elements,
# while np.random.permutation creates a new shuffled array without changing
# the original. You would use shuffle when you want to permanently change the order of an array,
# and permutation when you want a shuffled copy but still keep the original data unchanged.

## Mathematical Operations

### r_1 and r_2

In [9]:
print("r_1:\n", r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_2:\n", r_2)
print("Shape of r_2:", r_2.shape)

r_1:
 [7 1]
Shape of r_1: (2,)

r_2:
 [[4 4]]
Shape of r_2: (1, 2)


In [10]:
# Add function 
result_1 = np.add(r_1, r_2)
print("\nResult (r_1 + r_2):\n", result_1)
print("Shape of result:", result_1.shape)


Result (r_1 + r_2):
 [[11  5]]
Shape of result: (1, 2)


### r_1 + r_3

In [11]:
print("r_1:\n", r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_3:\n", r_3)
print("Shape of r_3:", r_3.shape)

r_1:
 [7 1]
Shape of r_1: (2,)

r_3:
 [[0.97151922]
 [0.22000754]]
Shape of r_3: (2, 1)


In [12]:
# Add r_1 + r_3
result_2 = np.add(r_1, r_3)
print("\nResult (r_1 + r_3):\n", result_2)
print("Shape of result:", result_2.shape)


Result (r_1 + r_3):
 [[7.97151922 1.97151922]
 [7.22000754 1.22000754]]
Shape of result: (2, 2)


### r_2 + r_4

In [13]:
print("r_2:\n", r_2)
print("Shape of r_2:", r_2.shape)

print("\nr_4:\n", r_4)
print("Shape of r_4:", r_4.shape)

r_2:
 [[4 4]]
Shape of r_2: (1, 2)

r_4:
 [[ 80  64  55  90  96]
 [100  47  38  43  64]
 [ 78  27  53  34  63]
 [ 84  30  94  45  80]]
Shape of r_4: (4, 5)


In [14]:
result_3 = np.add(r_2, r_4)
print("\nResult (r_2 + r_4):\n", result_3)
print("Shape of result:", result_3.shape)

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [15]:
# Error:
# This error occurs because the shapes (1,2) and (4,5) are not compatible.
# The number of columns (2 vs 5) do not match, and neither is 1,
# so NumPy cannot stretch the arrays to align.

### np.array([1]) to r_4

In [16]:
print(np.add(r_4, np.array([1])))

[[ 81  65  56  91  97]
 [101  48  39  44  65]
 [ 79  28  54  35  64]
 [ 85  31  95  46  81]]


### np.array([[1]]) to r_4

In [17]:
print(np.add(r_4, np.array([[1]])))

[[ 81  65  56  91  97]
 [101  48  39  44  65]
 [ 79  28  54  35  64]
 [ 85  31  95  46  81]]


### np.array([1,1,1,1,1]) to r_4

In [18]:
print(np.add(r_4, np.array([1, 1, 1, 1, 1])))

[[ 81  65  56  91  97]
 [101  48  39  44  65]
 [ 79  28  54  35  64]
 [ 85  31  95  46  81]]


### np.array([[1],[1]]) to r_4

In [20]:
result = np.add(r_4, np.array([[1], [1]]))
print(result)

ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

In [21]:
# Error:
# This produces a ValueError: operands could not be broadcast together with shapes (4,5) (2,1).
# The array (2,1) cannot be broadcast to match the shape (4,5) because
# the number of rows (2) does not match 4 and cannot be stretched.

# Rounding 

In [ ]:
### r_3 versions of rounding 

In [22]:
print("Original r_3:\n", r_3)
print()
# Truncate values (remove decimal, no rounding)
print("Trunc:\n", np.trunc(r_3))

Original r_3:
 [[0.97151922]
 [0.22000754]]

Trunc:
 [[0.]
 [0.]]


In [23]:
# Round toward zero
print("Fix:\n", np.fix(r_3))

Fix:
 [[0.]
 [0.]]


In [24]:
# Round down to nearest integer
print("Floor:\n", np.floor(r_3))

Floor:
 [[0.]
 [0.]]


In [25]:
# Round up to nearest integer
print("Ceil:\n", np.ceil(r_3))

Ceil:
 [[1.]
 [1.]]


In [26]:
# Round to 2 decimal places
print("Round (2 decimals):\n", np.round(r_3, 2))

Round (2 decimals):
 [[0.97]
 [0.22]]


## Cumulative Operations 

### r_4

In [27]:
# Display original r_4
print("r_4:\n", r_4)

r_4:
 [[ 80  64  55  90  96]
 [100  47  38  43  64]
 [ 78  27  53  34  63]
 [ 84  30  94  45  80]]


In [28]:
# Sum of all elements
print("Total sum:", np.sum(r_4))

Total sum: 1265


In [29]:
# Sum down each column
print("Sum along axis 0:\n", np.sum(r_4, axis=0))

Sum along axis 0:
 [342 168 240 212 303]


In [30]:
# Sum across each row
print("Sum along axis 1:\n", np.sum(r_4, axis=1))

Sum along axis 1:
 [385 292 255 333]


In [31]:
# Cumulative sum of all elements (flattened)
print("Cumulative sum:\n", np.cumsum(r_4))

Cumulative sum:
 [  80  144  199  289  385  485  532  570  613  677  755  782  835  869
  932 1016 1046 1140 1185 1265]


In [32]:
# Cumulative sum down columns
print("Cumulative sum along axis 0:\n", np.cumsum(r_4, axis=0))

Cumulative sum along axis 0:
 [[ 80  64  55  90  96]
 [180 111  93 133 160]
 [258 138 146 167 223]
 [342 168 240 212 303]]


## Grocery Problem 

In [42]:
# Order:
# Bag 1 contents
bag1 = {
    "vegetables": ["broccoli", "carrots"],
    "fruits": ["apples", "bananas", "grapes"],
    "snacks": ["chips", "cookies", "crackers", "granola bars"],
    "beverages": []
}

# Bag 2 contents
bag2 = {
    "vegetables": ["spinach", "peppers", "onions", "cucumbers"],
    "fruits": [],
    "snacks": ["pretzels"],
    "beverages": ["juice", "soda"]
}

In [43]:

bag1_array = np.array([
    len(bag1["vegetables"]),
    len(bag1["fruits"]),
    len(bag1["snacks"]),
    len(bag1["beverages"])
])
bag2_array = np.array([
    len(bag2["vegetables"]),
    len(bag2["fruits"]),
    len(bag2["snacks"]),
    len(bag2["beverages"])
])


In [44]:
total_bag1 = np.sum(bag1_array)
total_bag2 = np.sum(bag2_array)

In [45]:
print("Bag 1:", bag1_array)
print("Bag 2:", bag2_array)

Bag 1: [2 3 4 0]
Bag 2: [4 0 1 2]


In [46]:
print(f"The first bag contains {np.sum(bag1_array)} items, and the second bag contains {np.sum(bag2_array)} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [47]:
# Add totals by category
total_categories = bag1_array + bag2_array

# Print formatted sentence
print(f"There are {total_categories[0]} vegetables, {total_categories[1]} fruits, {total_categories[2]} boxes of snacks, and {total_categories[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


# Teamwork

In [48]:
# Ali: Monday → Friday
ali = np.array([5, 4, 6, 4, 2])
print("Ali:", ali)

Ali: [5 4 6 4 2]


In [49]:
# Ben missed Monday → use 0
ben = np.array([0, 5, 5, 3, 4])
print("Ben:", ben)

Ben: [0 5 5 3 4]


In [50]:
# Carla missed Wednesday → use 0
carla = np.array([3, 6, 0, 3, 4])
print("Carla:", carla)

Carla: [3 6 0 3 4]


In [51]:
# Combine into 2D array (rows = people, columns = days)
all_knocks = np.array([ali, ben, carla])
print("All Knocks:\n", all_knocks)

All Knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [52]:
# Total per person
total_per_person = np.sum(all_knocks, axis=1)

# Total for entire group
total_group = np.sum(all_knocks)

print("Total doors knocked per person:")
print(f"Ali: {total_per_person[0]}")
print(f"Ben: {total_per_person[1]}")
print(f"Carla: {total_per_person[2]}")

print(f"\nTotal doors knocked by the group: {total_group}")

Total doors knocked per person:
Ali: 21
Ben: 17
Carla: 16

Total doors knocked by the group: 54


In [53]:
#Total knocks per day
daily_totals = np.sum(all_knocks, axis=0)

# Rolling total of knocks
rolling_knocks = np.cumsum(daily_totals)

# Estimate votes (1 vote per 2 knocks)
estimated_votes = rolling_knocks * 0.5

print("Estimated votes (rolling total by day):\n", estimated_votes)


Estimated votes (rolling total by day):
 [ 4.  11.5 17.  22.  27. ]
